[package]
name = "xiao"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
opt-level = "s"
codegen-units = 1
panic = "abort"
strip = true
debug = false

[dependencies]
opus = "0.3"
anyhow = "1.0"
tokio = { version = "1.48", features = ["full"] }
tokio-util = { version = "0.7", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
postcard = { version = "1.0", features = ["alloc", "use-std"] }
parking_lot = "0.12.5"
dashmap = "6.1.0"
thiserror = "2.0.17"

[target.'cfg(target_os = "linux")'.dependencies]
alsa = "0.11"

[target.'cfg(not(target_os = "linux"))'.dependencies]
symphonia = { version = "0.5", features = ["mp3", "wav", "pcm"] }
